import React from 'react';
import { Shield, Sliders, AlertTriangle, BookOpen, ArrowRight, CheckCircle, HelpCircle, Layers, Cpu, Eye, FileText } from 'lucide-react';

export default function MethodologyPage({ onNavigate }) {
  return (
    <div className="methodology-page-container">
      <div className="container">
        {/* Header */}
        <header className="page-header">
          <span className="badge" style={{ backgroundColor: 'var(--bg-surface-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-default)', marginBottom: '8px' }}>
            System Architecture & Principles
          </span>
          <h1 className="page-title">Detection Methodology & Forensic Standards</h1>
          <p className="page-subtitle">
            An open specification of the forensic heuristics, confidence calibration protocols, and structural boundaries governing Authentix risk evaluation.
          </p>
        </header>

        {/* Section 1: Core Forensic Heuristics */}
        <section className="method-section">
          <h2 className="method-section-title">1. Multi-Vector Signal Extraction Pipeline</h2>
          <p className="method-text">
            Rather than relying on a single deep classifier that acts as a black box, Authentix divides analysis 
            into four distinct, mathematically grounded forensic domains:
          </p>

          <div className="method-cards-grid">
            <div className="card method-card">
              <div className="method-card-top">
                <span className="method-tag mono">SIGNAL_01</span>
                <Cpu size={20} className="text-action" />
              </div>
              <h3 className="method-card-title">Frequency Domain Analysis (2D-FFT)</h3>
              <p className="method-card-text">
                Generative models rely on upsampling operations (such as transposed convolutions or sub-pixel convolution) 
                to scale latent representations up to full pixel resolution. These operations introduce subtle, periodic 
                high-frequency artifacts. Authentix computes a 2D Fast Fourier Transform to identify energy spikes and 
                checkerboard frequency peaks that do not occur in natural optical lenses.
              </p>
            </div>

            <div className="card method-card">
              <div className="method-card-top">
                <span className="method-tag mono">SIGNAL_02</span>
                <Layers size={20} className="text-action" />
              </div>
              <h3 className="method-card-title">PRNU & Sensor Noise Consistency</h3>
              <p className="method-card-text">
                Physical digital camera sensors possess microscopic silicon imperfections that imprint a unique, 
                stochastic noise profile known as Photo-Response Non-Uniformity (PRNU) across the entire image. 
                Synthetic images generated by diffusion or autoregressive models either lack PRNU entirely or exhibit 
                discontinuous noise variances between the generated foreground and background plates.
              </p>
            </div>

            <div className="card method-card">
              <div className="method-card-top">
                <span className="method-tag mono">SIGNAL_03</span>
                <Eye size={20} className="text-action" />
              </div>
              <h3 className="method-card-title">Corneal & Optical Lighting Physics</h3>
              <p className="method-card-text">
                Synthetic generators frequently fail to maintain 3D spatial coherence across specular reflections. 
                In human subjects, Authentix evaluates the geometric orientation of corneal highlights (glints in the pupils) 
                against ambient light vectors cast across the nose, neck, and ears, flagging angular divergences greater than 10 degrees.
              </p>
            </div>

            <div className="card method-card">
              <div className="method-card-top">
                <span className="method-tag mono">SIGNAL_04</span>
                <FileText size={20} className="text-action" />
              </div>
              <h3 className="method-card-title">DCT Compression & Quantization Grids</h3>
              <p className="method-card-text">
                Standard JPEG compression partitions pixels into 8x8 discrete cosine transform (DCT) blocks. 
                When synthetic regions are spliced or generated images are saved without standard camera color transforms, 
                quantization error distributions diverge. Authentix detects double-compression traces and misaligned grid blocks.
              </p>
            </div>
          </div>
        </section>

        {/* Section 2: Calibrated Confidence */}
        <section className="method-section">
          <h2 className="method-section-title">2. Calibrated Confidence Intervals</h2>
          <div className="card method-callout-card">
            <h3 className="method-callout-title">The Fallacy of Raw Softmax Probabilities</h3>
            <p className="method-callout-text">
              Most commercial AI detectors output raw neural network softmax scores directly to the user (e.g., claiming "99.8% Fake"). 
              In machine learning research, it is well established that modern deep neural networks are drastically overconfident on 
              out-of-distribution samples and novel generator architectures.
            </p>
            <p className="method-callout-text" style={{ marginTop: '12px' }}>
              Authentix subjects all raw model logits to <strong>empirical calibration</strong> (Platt scaling and isotonic temperature scaling) 
              benchmarked against a continuous evaluation dataset of authentic camera captures and contemporary diffusion architectures 
              (Flux, Midjourney v6, SDXL, DALL-E 3). A 76% confidence score in Authentix signifies that historically, across identically 
              scored assets, exactly 76% were verified synthetic media.
            </p>
          </div>
        </section>

        {/* Section 3: Limitations & Boundary Conditions */}
        <section className="method-section">
          <h2 className="method-section-title">3. Operational Limitations & Edge Cases</h2>
          <p className="method-text">
            Integrity requires acknowledging where passive automated detection degrades. Authentix explicitly documents these vulnerabilities:
          </p>

          <div className="limitations-table-wrapper">
            <table className="method-table">
              <thead>
                <tr>
                  <th>Operational Factor</th>
                  <th>Observed Impact</th>
                  <th>Mitigation Protocol</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>Aggressive Re-compression</strong></td>
                  <td>Social media platforms re-encode images at low bitrates, eliminating fine Fourier and PRNU signals.</td>
                  <td>Model triggers an "Uncertain" verdict rather than guessing on degraded high frequencies.</td>
                </tr>
                <tr>
                  <td><strong>Generative Inpainting & Retouching</strong></td>
                  <td>Hybrid media where only an eye or garment is modified while the rest is authentic camera capture.</td>
                  <td>Local spatial bounding boxes isolate anomalous variances to prevent whole-image misclassification.</td>
                </tr>
                <tr>
                  <td><strong>Simulated Grain Injection</strong></td>
                  <td>Adversaries apply artificial film grain or Gaussian noise to mask diffusion signatures.</td>
                  <td>Multi-scale PRNU analysis differentiates synthetic uniform noise from silicon sensor noise profiles.</td>
                </tr>
                <tr>
                  <td><strong>Camera Post-Processing Pipelines</strong></td>
                  <td>Modern computational photography (e.g. night mode, HDR) applies multi-frame stitching that mimics synthesis.</td>
                  <td>DCT quantization checks and lens distortion profiles are cross-referenced to verify sensor physics.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* Section 4: Responsible Use Policy */}
        <section className="method-section">
          <h2 className="method-section-title">4. Responsible Deployment & Human-in-the-Loop</h2>
          <div className="card" style={{ borderColor: 'var(--border-default)' }}>
            <p className="method-card-text">
              Authentix is explicitly designed as a <strong>decision-support tool</strong>, not an autonomous adjudicator. 
              No media asset should be removed, censored, or subjected to punitive action based solely on an automated risk tier. 
              Human forensic investigators, journalists, and trust & safety analysts must retain final judgment, 
              using Authentix evidence breakdowns to corroborate context, provenance, and intent.
            </p>
            <div style={{ marginTop: 'var(--space-md)' }}>
              <button 
                className="btn btn-primary"
                onClick={() => onNavigate('upload')}
              >
                <span>Launch Analysis Console</span>
                <ArrowRight size={16} />
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
